### ISSUE TITLE
public link view count is not used correctly, bug with routing, bug with description

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#1124]
**sysPass Version**
v3 rv4

Hi @nuxsmin,

![grafik](https://user-images.githubusercontent.com/5631071/48969808-400e1400-f004-11e8-931d-034100a4ba4c.png)

i've tested something with the public links and found various problems:

When typing the max. duration i recognized the time unit is missing. Is it seconds, minutes, days, month? I found out that these are minutes. Please add a description. I also figured out that the maximum seems to be 52555. I entered 52600 and this was changed automatically to this decreased integer.

Next problem: I changed the max view count to 999. Syspass saves the value but it is not recognized for link renewal. If i renew a link there is only a maximum of 3 new allowed uses (this was the previous value). I also tried it out with value=10. No change.
![grafik](https://user-images.githubusercontent.com/5631071/48969854-3e911b80-f005-11e8-8ea7-c54665dded2a.png)

Another problem: The public link does not use the correct public URL - it used the one behind proxy. It's the same thing like in issue https://github.com/nuxsmin/sysPass/issues/1102. 

regards, Mario

**Comment by nuxsmin** [comment]
Hey, this was fixed in latest commit. Please check it out.

Thanks for the feedback!

**Comment by vmario89** [comment]
Hey @nuxsmin, the max count works now as exspected. Thanks also to adding the unit for time. The thing with URL was not fixed. It still shows proxied URL with port:
![grafik](https://user-images.githubusercontent.com/5631071/48985117-cb6ece80-f104-11e8-85e9-6fdd23012e42.png)

**Comment by nuxsmin** [comment]
About the URL, right I just (when answering the translations issue) noticed wasn't fixed indeed. I will need to add a configuration field for setting the real application URL, since PHP only "sees" the requested by the proxy...

Thanks for the feedback!
