### ISSUE TITLE
Does "sysPass Authenticator Plugin" work with syspass 3.2.0 docker

### ISSUE THREAD

**Issue by Elbje** [nuxsmin/sysPass#1636]
**sysPass Version**
docker image: syspass/syspass:3.2.0

**Describe the question**
Does the sysPass Authenticator Plugin work with version 3.2.0 of syspass? If so how do I get it working?
I am getting the following errors when I set the env var COMPOSER_EXTENSIONS to  "syspass/plugin-authenticator:^v2.1" :

```Text
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for syspass/extension-installer-plugin dev-master -> satisfiable by syspass/extension-installer-plugin[dev-master].
    - syspass/extension-installer-plugin dev-master requires composer-plugin-api ^2.0 -> no matching package found.
  Problem 2
    - syspass/extension-installer-plugin v2.0.x-dev requires composer-plugin-api ^2.0 -> no matching package found.
    - syspass/extension-installer-plugin dev-master requires composer-plugin-api ^2.0 -> no matching package found.
    - syspass/extension-installer-plugin dev-develop requires composer-plugin-api ^2.0 -> no matching package found.
    - syspass/plugin-authenticator v2.1.0 requires syspass/extension-installer-plugin * -> satisfiable by syspass/extension-installer-plugin[dev-develop, dev-master, v2.0.x-dev].
    - Installation request for syspass/plugin-authenticator ^v2.1 -> satisfiable by syspass/plugin-authenticator[v2.1.0].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it
```

**Screenshots**
![image](https://user-images.githubusercontent.com/43099137/103220666-2812c800-4921-11eb-9810-018650f47094.png)

**Platform (please complete the following information):**
 - OS: Ubuntu
 - OS Version: 18.04
 - Docker Version: Docker version 20.10.1, build 831ebea
**Additional context**
I am already using the plugin (v2.0) with syspass v3.1.0. I was trying to update syspass to v3.2.0 when I ran into this issue
Also: when I revert to v3.1.0 the plugin does not work anymore...

**Comment by gruffatremi** [comment]
Hey, 
I am not using the docker version, but I still can't make it work. I've been able to install it but it tell me that it's not compatible : 
![image](https://user-images.githubusercontent.com/71137818/103915065-feb91f80-510a-11eb-833d-e9f86c5ee9cd.png)
Regards,

**Comment by nuxsmin** [comment]
Hello,

sorry for the inconvenience. I've just released out a new plugin's version which is compatible with the latest sysPass version. What does change?: It's focused on making dependencies compatible, because many sysPass dependencies were updated and they require a maintanied PHP version, so sysPass needed to be updated in order to update its dependencies.

Please let me know if it works fine after this update.

Regards

**Comment by gruffatremi** [comment]
> 
> 
> Hello,
> 
> sorry for the inconvenience. I've just released out a new plugin's version which is compatible with the latest sysPass version. What does change?: It's focused on making dependencies compatible, because many sysPass dependencies were updated and they require a maintanied PHP version, so sysPass needed to be updated in order to update its dependencies.
> 
> Please let me know if it works fine after this update.
> 
> Regards

Thank you it totally work : 
I had to delete both composer.json and composer.lock, then git pull to update and then composer require syspass/plugin-authenticator:^v2.2.1 and it worked :) 
Thank you 👍

**Comment by Elbje** [comment]
Hello,

Thanks for the reply, however I am still experiencing issues. I am using the docker version and I still can't get it to work.. I've used syspass version 3.2.1 and 3.2.0 with a combination of authenticator version v2.1.1 - v2.2.1 but I always get dependency errors:

```text

entrypoint: Starting with UID : 9001
setup_app: Setting up permissions
setup_composer_extensions: syspass/plugin-authenticator:v2.2.1
~ /var/www/html
run_composer: Running composer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for syspass/extension-installer-plugin v2.0.0 -> satisfiable by syspass/extension-installer-plugin[v2.0.0].
    - syspass/extension-installer-plugin v2.0.0 requires composer-plugin-api ^2.0 -> no matching package found.
  Problem 2
    - syspass/extension-installer-plugin v2.0.0 requires composer-plugin-api ^2.0 -> no matching package found.
    - syspass/plugin-authenticator v2.2.1 requires syspass/extension-installer-plugin ^2.0 -> satisfiable by syspass/extension-installer-plugin[v2.0.0].
    - Installation request for syspass/plugin-authenticator v2.2.1 -> satisfiable by syspass/plugin-authenticator[v2.2.1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.

Installation failed, reverting ./composer.json to its original content.
```

Kind regards

**Comment by Elbje** [comment]
Any updates regarding this issue?
