### ISSUE TITLE
Internal Server Errorerror

### ISSUE THREAD

**Issue by zulink** [nuxsmin/sysPass#380]
Hello! 
I really love Syspass,  I was really glad about Syspass 2.0

But i have a problem
When i have install syspass2.0 i have error
No /var/log/apache2/error.log shows nothing.
I Deleted database and users,  I am trying install  by this instuction https://wiki.syspass.org/en/hostingmode , but it's not worked

Help please :)

<img width="356" alt="123" src="https://cloud.githubusercontent.com/assets/25300170/22207812/b91bd2a2-e191-11e6-86b9-e972eba4c985.png">
<img width="490" alt="456" src="https://cloud.githubusercontent.com/assets/25300170/22207818/bb9188b0-e191-11e6-886c-d1f86ab2a4d2.png">
<img width="482" alt="101112" src="https://cloud.githubusercontent.com/assets/25300170/22207822/bdf409ca-e191-11e6-8684-e48b61138b78.png">

**Comment by nuxsmin** [comment]
Hello! I'm very glad too that you liked sysPass :)

Which build version are you trying to install?. Did you get the latest one (at GitHub releases page)?

Kind regards

**Comment by zulink** [comment]
I downloaded from here, https://github.com/nuxsmin/sysPass/releases , at this moment it's last version.
Probably :)

![image](https://cloud.githubusercontent.com/assets/25300170/22209359/416a3360-e197-11e6-8db6-6abef6bbbff6.png)

**Comment by nuxsmin** [comment]
Sure, that it the latest...

Did you check the hosting mode check?. There were some behaviors when using weak mysql user passwords, so it should contain lower&upper case letters, numbers and symbols, because MySQL would let you create the user but the login is denied.

Is there any error in the webserver (apache?) log?

**Comment by zulink** [comment]
> Did you check the hosting mode check?. There were some behaviors when using weak mysql user passwords, so it should contain lower&upper case letters, numbers and symbols, because MySQL would let you create the user but the login is denied.

Tomorrow I will try this and write you about results

> Is there any error in the webserver (apache?) log?

No, logs completely empty :(


Thanks you for fast answer!

**Comment by nuxsmin** [comment]
Great! Le me know if there is any progress.

You're welcome

**Comment by nuxsmin** [comment]
I've released some fixes for this kind of issue, can you try it out?

**Comment by zulink** [comment]
> I've released some fixes for this kind of issue, can you try it out?

Yes i download and install
![image](https://cloud.githubusercontent.com/assets/25300170/22245237/036a4e84-e240-11e6-8f56-4913bc26c7be.png)

It's not solved my problem :((
<img width="481" alt="131415" src="https://cloud.githubusercontent.com/assets/25300170/22245272/2b4a4a26-e240-11e6-91c5-7be604f60c09.png">

Syspass 1.2 work correct

**Comment by nuxsmin** [comment]
Is there any error in the webserver error log?

**Comment by nuxsmin** [comment]
It stores them in the error.log (Apache) file.

**Comment by zulink** [comment]
Oooups, my mistake, a disable logs

That in logs


access.log
```
192.168.18.162 - - [24/Jan/2017:17:46:52 +0300] "POST /syspass/ajax/ajax_install.php HTTP/1.1" 200 615 "http://syspass.ulmart.ru/syspass/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"
192.168.18.162 - - [24/Jan/2017:17:46:59 +0300] "POST /syspass/ajax/ajax_install.php HTTP/1.1" 500 343 "http://syspass.ulmart.ru/syspass/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"

```

error.log
```
[Tue Jan 24 17:46:35.788232 2017] [mpm_prefork:notice] [pid 3306] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.20 configured -- resuming normal operations
[Tue Jan 24 17:46:35.788361 2017] [core:notice] [pid 3306] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jan 24 17:47:00.368434 2017] [:error] [pid 3310] [client 192.168.18.162:11174] Action: Configuraci\xc3\xb3n -- Description: Modificar configuraci\xc3\xb3n -- Details: , referer: http://syspass.ulmart.ru/syspass/
[Tue Jan 24 17:47:00.391887 2017] [:error] [pid 3310] [client 192.168.18.162:11174] PHP Fatal error:  Call to undefined function SP\\Core\\hash_equals() in /var/www/html/syspass/inc/SP/Core/Crypt.class.php on line 141, referer: http://syspass.ulmart.ru/syspass/

```

**Comment by nuxsmin** [comment]
Ok, that is because the PHP version is below 5.6, isn't it?

**Comment by nuxsmin** [comment]
The PHP version checking during the install process was broken.

**Comment by zulink** [comment]
> Ok, that is because the PHP version is below 5.6, isn't it?

> The PHP version checking during the install process was broken

I tried to install another version of PHP, it does't help:(

I try instal server “from scratch” and  ubuntu 16.04, I tell how it's done

**Comment by nuxsmin** [comment]
Did it throw any error in the event log?

**Comment by zulink** [comment]
Reinstall the system on ubutnu 16.04, the problem is solved!
Looks like the problem in my side

Thank you very much for the help!!
I will continue to love syspass, you best!

Have a nice day :+1:

**Comment by nuxsmin** [comment]
That sounds great!! Thanks for the feedback ;)
