### ISSUE TITLE
getting stuck during the installation

### ISSUE THREAD

**Issue by malumba** [nuxsmin/sysPass#44]
I'm trying to install version 1.0.9 of syspass but I'm getting stuck after I offered the required Information and clicked on the install button. The Browser only shows a blank page. In the PHP error log I got several errors:

```
mod_fcgid: stderr: PHP Warning:  mysqli::real_escape_string(): Couldn't fetch mysqli in /httpdocs/inc/db.class.php on line 84, referer: https://name.tld/index.php

mod_fcgid: stderr: PHP Warning:  mysqli::query(): Couldn't fetch mysqli in /httpdocs/inc/db.class.php on line 106, referer: https://name.tld/index.php

mod_fcgid: stderr: PHP Warning:  DB::doQuery(): Couldn't fetch mysqli in /httpdocs/inc/db.class.php on line 109, referer: https://name.tld/index.php

mod_fcgid: stderr: PHP Warning:  DB::doQuery(): Couldn't fetch mysqli in /httpdocs/inc/db.class.php on line 112, referer: https://name.tld/index.php

mod_fcgid: stderr: pdocs/inc/db.class.php on line 84, referer: https://name.tld/index.php
```

These error messages do repeat very often.

Finally the log ends with a fatal error:

```
mod_fcgid: stderr: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted
```

In the database columns were created but there is no data inside.
I'm in a Plesk (http://www.parallels.com/products/plesk/) environment with Apache, Ngnix, MYSQL and PHP 5.5.13. It doesn't make sense to change the user of config and backup folder to www-data like it is mentioned in the installation documentation because that's not working with Plesk. User of the files/folders has to be the user which is the owner of the webspace. I can only set the group to a group that has got the same rights like www-data. Then I have to change the rights of config folder to 770 instead of 750. But then the install script does not start because of that.
Do you've got any idea what to do next?

Best regards
Chris

**Comment by mape2k** [comment]
When installing syspass-1.1.2.23 i'm running in the same issue. Using database user/pass as admin user/pass works. But this is an issue which should be fixed!

**Comment by nuxsmin** [comment]
Hi @mape2k what kind of issues are still present?

The first user/pass fileds are to log in sysPass and the user is also used to create the sysPass database user for its connection by prefixing it with "sp_".

The second user/pass fields are only to create the sysPass database and its connection user.

**Comment by mape2k** [comment]
This is not intuitive :(

I expect the first user/pass is for the administrative user and the second one for the database - especially if hosting mode is enabled. This is what most users will expect.

**Comment by nuxsmin** [comment]
First field help of "Create sysPass admin account" legend says "sysPass's administrators login".
First field help of "DB Configuration (MySQL)" legend says "User login with database administrative rights".

Can you help me to improve it?

This install page was mainly based on the Owncloud one, with some changes. I tried to make a minimalistic install process that was self described, so by filling some required information it would take 1 minute to install.

![owncloud_install](https://cloud.githubusercontent.com/assets/1775774/7752224/94b4c6e4-ffde-11e4-876e-904fbba88bba.png)

**Comment by mape2k** [comment]
owncloud is a good example. the admin account is here what i said: the admin account for owncloud. the informations are not used for database.

The database informations at the bottom are used to connect to the database. Database user and database itself have to exists already when installing owncloud. This is a usual approach. 

I don't know any web application which creates the database user and database herself - except sysPass. E.g. in shared hosting environments this is really unusal. If you'd like to provide such a feature there should be 2 more inputs for requesting database-superuser and his password if Hosting mode ist "off". There should be also an information about "hosting mode" and why database-superuser is needed.

IMHO this feature is unneeded cause it is unusual.

**Comment by nuxsmin** [comment]
Sorry, but if the Owncloud installation process have not changed since a year ago, the Owncloud admin account is also used as the db connection user (prefixing by "oc_").

Recently, I've added some info about hosting mode at http://wiki.syspass.org/en/hostingmode

**Comment by mape2k** [comment]
Regarding
https://doc.owncloud.org/server/8.0/admin_manual/installation/installation_wizard.html#storage-database
https://doc.owncloud.org/server/8.0/admin_manual/configuration_database/linux_database_configuration.html
and my memories last time i installed owncloud in March the user and database have to be created before. Maybe it also works as you described, but IMHO this is common unusual.

And so there's no possibility to create a admin user which is not the same as the database user in hosting mode.

**Comment by nuxsmin** [comment]
You're right about hosting mode behavior, it uses the same user for the app and database connection, but it's just to keep a clear/simple install process and don't take more inputs from the users. BTW you can change user login once installed.

Although, all opinions are welcome and I'll take them into account for next builds/releases

**Comment by nuxsmin** [comment]
...thanks for the feedback ;)
