### ISSUE TITLE
Fail to Install

### ISSUE THREAD

**Issue by juanfernandovillahernandez** [nuxsmin/sysPass#495]
When I try to install the web page it's in blank.
Checking the logs this appears:
PHP Fatal error:  Call to undefined function SP\\Core\\Crypt\\hash_equals() in /var/www/html/syspassx/inc/SP/Core/Crypt/Cookie.class.php on line 60
Somebody can help me? thanks in advance.

**Comment by nuxsmin** [comment]
Hello,
that is because sysPass >= 2.1 version requires PHP 5.6 or higher.

Regards

**Comment by juanfernandovillahernandez** [comment]
I just update but this log appear:
PHP Fatal error:  Call to undefined function SP\\Core\\Crypt\\hash_equals() in /var/www/html/syspassx/inc/SP/Core/Crypt/Cookie.class.php on line 60
PHP Stack trace:
PHP   1. {main}() /var/www/html/syspassx/index.php:0
PHP   2. require() /var/www/html/syspassx/index.php:31
PHP   3. SP\\Core\\Init::start() /var/www/html/syspassx/inc/Base.php:118
PHP   4. SP\\Core\\Init::startSession() /var/www/html/syspassx/inc/SP/Core/Init.class.php:117
PHP   5. SP\\Core\\Crypt\\SecureKeyCookie::getKey() /var/www/html/syspassx/inc/SP/Core/Init.class.php:303
PHP   6. SP\\Core\\Crypt\\Cookie->getCookieData() /var/www/html/syspassx/inc/SP/Core/Crypt/SecureKeyCookie.class.php:65
What do you suggest?

**Comment by nuxsmin** [comment]
Sorry, that commit comments is related to another issue.

This issue is because the minimum PHP version, which need to be 5.6 .

The version check takes place after the session handling so that's because you get a blank screen.

To sum up, please update PHP version.

**Comment by Sispheor** [comment]
Hi, you should update [your doc then for Centos 7](https://doc.syspass.org/en/installing/centos7.html). 
I had to follow [this doc](https://webtatic.com/packages/php56/) to install php 5.6. 
I can now install syspass but the ldap module is disabled. I cannot install it. There is a conflict with php-common.
```
yum -y install php-ldap
Loaded plugins: replace
Resolving Dependencies
--> Running transaction check
---> Package php-ldap.x86_64 0:5.4.16-42.el7 will be installed
--> Processing Dependency: php-common(x86-64) = 5.4.16-42.el7 for package: php-ldap-5.4.16-42.el7.x86_64
--> Running transaction check
---> Package php-common.x86_64 0:5.4.16-42.el7 will be installed
--> Processing Conflict: php56w-common-5.6.30-1.w7.x86_64 conflicts php-common < 5.6
--> Finished Dependency Resolution
Error: php56w-common conflicts with php-common-5.4.16-42.el7.x86_64
```

Do you have a pointer for an installation of everything properly on CentOS 7 with the last version?

Thanks.

**Comment by nuxsmin** [comment]
Hi @Sispheor you're right, that CentOS guide is a bit older...

As you pointed, you would need to install an alternate php5.6 package which, in this case, would need its own common package, so the ' php-common` package need to be replaced with `php56w-common`

Currently I haven't tested yet the CentOS installation. I'll do it shortly.

Regards

**Comment by juanfernandovillahernandez** [comment]
Same issue. This it's my versión: PHP 5.5.9-1ubuntu4.21 (cli) (built: Feb  9 2017 20:54:58)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
    with Xdebug v2.2.3, Copyright (c) 2002-2013, by Derick Rethans

**Comment by nuxsmin** [comment]
Sorry, but sysPass >2 will only work on PHP 5.6 or higher (<7.1) because it uses some functions needed for advanced encryption and other features.

**Comment by juanfernandovillahernandez** [comment]
Installed. But fail again:
PHP 5.6.30-7+deb.sury.org~trusty+1 (cli)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2016-01-05T00:00:00
[13-Mar-2017 14:21:05 America/Bogota] PHP Fatal error:  Call to undefined function SP\Core\Crypt\hash_equals() in /var/www/html/syspass/inc/SP/Core/Crypt/Cookie.class.php on line 60
[13-Mar-2017 14:21:05 America/Bogota] PHP Stack trace:
[13-Mar-2017 14:21:05 America/Bogota] PHP   1. {main}() /var/www/html/syspass/index.php:0
[13-Mar-2017 14:21:05 America/Bogota] PHP   2. require() /var/www/html/syspass/index.php:31
[13-Mar-2017 14:21:05 America/Bogota] PHP   3. SP\Core\Init::start() /var/www/html/syspass/inc/Base.php:118
[13-Mar-2017 14:21:05 America/Bogota] PHP   4. SP\Core\Init::startSession() /var/www/html/syspass/inc/SP/Core/Init.class.php:117
[13-Mar-2017 14:21:05 America/Bogota] PHP   5. SP\Core\Crypt\SecureKeyCookie::getKey() /var/www/html/syspass/inc/SP/Core/Init.class.php:303
[13-Mar-2017 14:21:05 America/Bogota] PHP   6. SP\Core\Crypt\Cookie->getCookieData() /var/www/html/syspass/inc/SP/Core/Crypt/SecureKeyCookie.class.php:65

**Comment by nuxsmin** [comment]
It's so weird because it's part of the PHP core: http://php.net/manual/en/hash.requirements.php and http://php.net/manual/en/function.hash-equals.php

**Comment by nuxsmin** [comment]
Please check out the `phpinfo()` output by placing this code into a php file:

```
<?php
  phpinfo();
```
It should output this:

![002](https://cloud.githubusercontent.com/assets/1775774/23872583/2055da80-082f-11e7-8304-5bf437e8576e.png)

**Comment by juanfernandovillahernandez** [comment]
hash
hash support 	enabled
Hashing Engines 	md2 md4 md5 sha1 sha224 sha256 sha384 sha512 ripemd128 ripemd160 ripemd256 ripemd320 whirlpool tiger128,3 tiger160,3 tiger192,3 tiger128,4 tiger160,4 tiger192,4 snefru snefru256 gost adler32 crc32 crc32b fnv132 fnv164 joaat haval128,3 haval160,3 haval192,3 haval224,3 haval256,3 haval128,4 haval160,4 haval192,4 haval224,4 haval256,4 haval128,5 haval160,5 haval192,5 haval224,5 haval256,5

**Comment by nuxsmin** [comment]
Really weird...I'm trying to find out what could be happening, because it's trying to call a function (`SP\Core\Crypt\hash_equals()`) inside the class, but it's a global function instead.

**Comment by juanfernandovillahernandez** [comment]
:(  Well. I will try combinations to find a correct env. I expect find the situation or bug of the syspass. Thanks anyway. Syspass it's a awesome web app. Go on!

**Comment by nuxsmin** [comment]
Fine, I'd like that you would be able to run sysPass without this weird issue.

Gracias por la información!

**Comment by juanfernandovillahernandez** [comment]
PLOP! My Fault. Sorry! I forgot disable module php5 and enable php5.6 in apache
How I fixed:
sudo add-apt-repository ppa:ondrej/php
sudo apt-get install software-properties-common
sudo apt-get update
sudo apt-get install php5.6
sudo apt-get install php5.6-mbstring php5.6-mcrypt php5.6-mysql php5.6-xml
sudo a2dismod php5
sudo a2enmod php5.6
sudo service apache restart
Thats all!
Best Regards!

**Comment by nuxsmin** [comment]
That's great!..umm, does not Ubuntu ship with PHP 5.6?. I'm using Debian 8 and it's bundled by default.

Thanks for the feedback!

**Comment by Sispheor** [comment]
Should I open a new issue for the CentOS 7 install?

I'll give a try with `php56w-common`.
But php-ldap is based on php-common as dependency and so it will still fail to install I think.

**Comment by Sispheor** [comment]
It's ok with `php56w-ldap`
