### ISSUE TITLE
LDAP user import not working

### ISSUE THREAD

**Issue by ReeceYoung98** [nuxsmin/sysPass#561]
Hi,

Loving using sysPass for our organisation.

I have successfully setup the configuration for the LDAP configuration and testing the connection brings out the users I would like to import.

Clicking on the import button declares it was successful although looking at the logs, it displays:
'LDAP users import finished
Imported users : 0/721
Errors : 0'

None of the users are imported.

Below is a screenshot of what I'm trying to use:
[Image of config](http://imgur.com/a/YCELf)

Also, the two bottom settings don't save as to my choice I have selected.

**Comment by nuxsmin** [comment]
Hello,

The two buttons below are only for importing the users, so you would need to set them to your LDAP attributes. If those options are not correctly set the import would fail, because the login and​ name attributes should be retrieved from LDAP.

**Comment by ReeceYoung98** [comment]
Hi,

Yes, the values that are in the picture are what my attributes in the LDAP are. Is it case sensitive as if so, the casing is wrong for my attributes in LDAP?

**Comment by nuxsmin** [comment]
Ok, don't worry about the case, it will be checked in lowercase.

As I said, if either the login or  username aren't set, the users won't be imported

**Comment by nuxsmin** [comment]
Currently I'm not on my computer, so I couldn't check out the code to figure out what could be happening.

Thanks for feedback!

And so glad that you found sysPass useful :)

**Comment by nuxsmin** [comment]
Could you tell me which LDAP server are you using?. It's really weird that none of the users were imported.

**Comment by nuxsmin** [comment]
I'm trying to figure out what could be happening, although you could log into sysPass with LDAP users, because they will be created if don't exist. The default group and profile will be used for the newly created users.

**Comment by ReeceYoung98** [comment]
Error while searching the user on LDAP
User : <username>
LDAP ERROR : Success (0)
LDAP FILTER :
(&(|(samaccountname=<username>)(cn=<username>)(uid=<username>))(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject))(objectCa
tegory=person))

It then reverts to using authDatabase, as it can't find user from LDAP query although query succeeds using Powershell. The query also works when using the 'Check' button.

**Comment by nuxsmin** [comment]
Hi, the LDAP import should be fixed in the latest commit.

**Comment by ReeceYoung98** [comment]
LDAP import still isn't working unfortunately.

Running 'ldapsearch -W -x -b "dc=authorise,dc=xxx,dc=xxx,dc=xxx" -D "uid=username,ou=people,ou=central,dc=authorise,dc=xxx,dc=xxx,dc=xxx" -H ldaps://authorise.is.ed.ac.uk:636/dc=authorise/dc=xxx/dc=xxx/dc=xxx "cn=D834"' gives the following for each user: 'member: uid=username,ou=people,ou=central,dc=authorise,dc=xxx,dc=xxx,dc=xxx'

Returns the full list of my LDAP users. The import still doesn't create users.

Even trying to login as an LDAP user, to verify gives the following errors:

**2017-05-05 08:42:48	ERROR	Log in		IP	Wrong login**
Type : authBrowser
User : username
Authentication : COSIGN ()
**2017-05-05 08:42:48	ERROR	getUserAttributes		IP	Error while** searching the user on LDAP
User : username
LDAP ERROR : Success (0)
LDAP FILTER :
(&(|(samaccountname=username)(cn=username)(uid=username))(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject))(objectCategory=person))

**Comment by nuxsmin** [comment]
Ummm, is that the only attribute returned by the searching? (`member: uid=username,ou=people,ou=central,dc=authorise,dc=xxx,dc=xxx,dc=xxx`)

Could you strip the `dc=authorise/dc=xxx/dc=xxx/dc=xxx` from the connection string?. It isn't needed for this kind of connection.

Regarding the "Wrong login" message, are you using SSO? (https://en.wikipedia.org/wiki/CoSign_single_sign_on) If so, your webserver is sending some authentication headers, so sysPass will check the SSO username against the username provided on the login, if they don't match, login will be denied...

**Comment by ReeceYoung98** [comment]
On the basic search, yes, but selecting a specific user gives much more.
The two I'm selecting on the LDAP import page is:
- uid: username
- cn: Reece Young
I'm using these two for the username and login attributes as they're the ones we make use of.

I've stripped the connection string and no difference was made. I'll leave that out.

We are using Cosign to protect the entire website - we'd look to remove the cosign once we have the LDAP functionality - would it be best if I just remove cosign for now?

**Comment by ReeceYoung98** [comment]
Disabling the cosign protection had no affect - LDAP search is still performed but returns LDAP ERROR : Success (0).

**Comment by nuxsmin** [comment]
Ok, Cosign will interfere when logging in (because said above), but it won't make LDAP to work.

I've just pushed a new commit to fix the import behavior because the `cn` attribute was not retrieved when importing. Please try it out from the master branch (https://github.com/nuxsmin/sysPass/archive/master.zip)

Regarding the LDAP searching issue, it would be useful to activate the debug mode on the "Configuration > Site" tab, so it will output a bunch of messages in the webserver error log. Be aware that some private info will be logged, so you would need to skip them.

**Comment by ReeceYoung98** [comment]
The user import now works - thanks.

Trying to login as an imported user still gives off the same error.

Error while searching the user on LDAP
User : username
LDAP ERROR : Success (0)
LDAP FILTER :
(&(|(samaccountname=username)(cn=username)(uid=username))(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject))(objectCategory=person))

It then defaults back to:
Wrong login
Type : authBrowser
User : eusasys1

From Debug:
            [ldapBase:SP\Config\ConfigData:private] => dc=authorise,dc=xxx,dc=xxx,dc=xxx
            [ldapBindUser:SP\Config\ConfigData:private] => uid=username,ou=people,ou=central,dc=authorise,dc=xxx,dc=xxx,dc=xxx
            [ldapBindPass:SP\Config\ConfigData:private] => password
            [ldapProxyUser:SP\Config\ConfigData:private] => 
            [ldapEnabled:SP\Config\ConfigData:private] => 1
            [ldapAds:SP\Config\ConfigData:private] => 1
            [ldapGroup:SP\Config\ConfigData:private] => D834
            [ldapServer:SP\Config\ConfigData:private] => ldaps://authorise.xxx.xxx.xxx.xxx:636/dc=authorise/dc=xxx/dc=xxx/dc=xxx
            [ldapUserattr:SP\Config\ConfigData:private] => 


ldap_create
ldap_url_parse_ext(ldaps://authorise.xxx.xxx.xxx.xxx:636)
ldap_sasl_bind_s
ldap_sasl_bind
ldap_send_initial_request
ldap_new_connection 1 1 0
ldap_int_open_connection
ldap_connect_to_host: TCP authorise.xxx.xxx.xxx.xxx:636
ldap_new_socket: 19
ldap_prepare_socket: 19
ldap_connect_to_host: Trying IP ADDR
ldap_pvt_connect: fd: 19 tm: 10 async: 0
ldap_ndelay_on: 19
attempting to connect: 
connect errno: 115
ldap_int_poll: fd: 19 tm: 10
ldap_is_sock_ready: 19
ldap_ndelay_off: 19
ldap_pvt_connect: 0
TLS: certdb config: configDir='/etc/openldap/certs' tokenDescription='ldap(0)' certPrefix='' keyPrefix='' flags=readOnly
TLS: using moznss security dir /etc/openldap/certs prefix .
TLS: certificate [CN=authorise.xxx.xxx.xxx.xxx,CERTIFICATE DETAILS REMOVED
TLS certificate verification: subject: CN=authorise.xxx.xxx.xxx.xxx,CERTIFICATE DETAILS REMOVED
ldap_open_defconn: successful
ldap_send_server_request
ldap_result ld 0x7f1672915540 msgid 1
wait4msg ld 0x7f1672915540 msgid 1 (infinite timeout)
wait4msg continue ld 0x7f1672915540 msgid 1 all 1
** ld 0x7f1672915540 Connections:
* host: authorise.xxx.xxx.xxx.xxx  port: 636  (default)
  refcnt: 2  status: Connected
  last used: Fri May  5 12:16:33 2017


** ld 0x7f1672915540 Outstanding Requests:
 * msgid 1,  origid 1, status InProgress
   outstanding referrals 0, parent count 0
  ld 0x7f1672915540 request count 1 (abandoned 0)
** ld 0x7f1672915540 Response Queue:
   Empty
  ld 0x7f1672915540 response count 0
ldap_chkResponseList ld 0x7f1672915540 msgid 1 all 1
ldap_chkResponseList returns ld 0x7f1672915540 NULL
ldap_int_select
read1msg: ld 0x7f1672915540 msgid 1 all 1
read1msg: ld 0x7f1672915540 msgid 1 message type bind
read1msg: ld 0x7f1672915540 0 new referrals
read1msg:  mark request completed, ld 0x7f1672915540 msgid 1
request done: ld 0x7f1672915540 msgid 1
res_errno: 0, res_error: <>, res_matched: <>
ldap_free_request (origid 1, msgid 1)
ldap_parse_result
ldap_msgfree
ldap_search_ext
put_filter: "(&(|(samaccountname=username)(cn=username)(uid=username))(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject))(objectCategory=person))"
put_filter: AND
put_filter_list "(|(samaccountname=username)(cn=username)(uid=username))(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject))(objectCategory=person)"
put_filter: "(|(samaccountname=username)(cn=username)(uid=username))"
put_filter: OR
put_filter_list "(samaccountname=username)(cn=username)(uid=username)"
put_filter: "(samaccountname=username)"
put_filter: simple
put_simple_filter: "samaccountname=username"
put_filter: "(cn=username)"
put_filter: simple
put_simple_filter: "cn=username"
put_filter: "(uid=username)"
put_filter: simple
put_simple_filter: "uid=username"
put_filter: "(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject))"
put_filter: OR
put_filter_list "(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject)"
put_filter: "(objectClass=inetOrgPerson)"
put_filter: simple
put_simple_filter: "objectClass=inetOrgPerson"
put_filter: "(objectClass=person)"
put_filter: simple
put_simple_filter: "objectClass=person"
put_filter: "(objectClass=simpleSecurityObject)"
put_filter: simple
put_simple_filter: "objectClass=simpleSecurityObject"
put_filter: "(objectCategory=person)"
put_filter: simple
put_simple_filter: "objectCategory=person"
ldap_build_search_req ATTRS: dn displayname samaccountname mail memberof lockouttime fullname groupmembership uid givenname sn userprincipalname cn
ldap_send_initial_request
ldap_send_server_request
ldap_result ld 0x7f1672915540 msgid 2
wait4msg ld 0x7f1672915540 msgid 2 (infinite timeout)
wait4msg continue ld 0x7f1672915540 msgid 2 all 1
** ld 0x7f1672915540 Connections:
* host: authorise.xxx.xxx.xxx.xxx  port: 636  (default)
  refcnt: 2  status: Connected
  last used: Fri May  5 12:16:33 2017


** ld 0x7f1672915540 Outstanding Requests:
 * msgid 2,  origid 2, status InProgress
   outstanding referrals 0, parent count 0
  ld 0x7f1672915540 request count 1 (abandoned 0)
** ld 0x7f1672915540 Response Queue:
   Empty
  ld 0x7f1672915540 response count 0
ldap_chkResponseList ld 0x7f1672915540 msgid 2 all 1
ldap_chkResponseList returns ld 0x7f1672915540 NULL
ldap_int_select
read1msg: ld 0x7f1672915540 msgid 2 all 1
read1msg: ld 0x7f1672915540 msgid 2 message type search-result
read1msg: ld 0x7f1672915540 0 new referrals
read1msg:  mark request completed, ld 0x7f1672915540 msgid 2
request done: ld 0x7f1672915540 msgid 2
res_errno: 0, res_error: <>, res_matched: <>
ldap_free_request (origid 2, msgid 2)
ldap_parse_result
ldap_msgfree
ldap_err2string
ldap_free_connection 1 1
ldap_send_unbind
ldap_free_connection: actually freed

**Comment by nuxsmin** [comment]
Please, use this gist https://gist.github.com/nuxsmin/a6b2f2701ce8b78ceadd835adc26756a to check if there is any result from the search query (fill in with your own data).

You can place it anywhere in the webserver root and then point your browser to that file.

**Comment by ReeceYoung98** [comment]
## Group Filter (regex): 
Array
(
    [0] => cn=D834
    [1] => cn=D834
)
## Group Entries: 
Array
(
    [count] => 1
    [0] => Array
        (
            [cn] => Array
                (
                    [count] => 1
                    [0] => D834
                )

            [0] => cn
            [count] => 1
            [dn] => cn=D834,ou=D834,ou=P99,ou=NSU3,ou=NSU,ou=xxx,ou=org,ou=grouper2,dc=authorise,dc=xxx,dc=xxx,dc=xxx
        )

)
## User Filter: 
(memberof:1.2.840.113556.1.4.1941:=cn=D834,ou=D834,ou=P99,ou=NSU3,ou=NSU,ou=xxx,ou=org,ou=grouper2,dc=authorise,dc=xxx,dc=xxx,dc=xxx)## User Entries: 
Array
(
    [count] => 0
)

**Comment by nuxsmin** [comment]
Umm, the search didn't find any result for the given user...

Does the group DN match with the group that the user is member of?, Is the user a member of that group?

Thanks for testing!

**Comment by ReeceYoung98** [comment]
Yes, the Group DN is what the user was imported using.

That was for the group. Below is setting the group DN to uid=

## Group Filter (regex): 
Array
(
)
## Group Entries: 
Array
(
    [count] => 1
    [0] => Array
        (
            [cn] => Array
                (
                    [count] => 1
                    [0] => Reece Young
                )

            [0] => cn
            [count] => 1
            [dn] => uid=v1ryoun7,ou=people,ou=central,dc=authorise,dc=xxx,dc=xxx,dc=xxx
        )

)
## User Filter: 
(memberof:1.2.840.113556.1.4.1941:=uid=v1ryoun7,ou=people,ou=central,dc=authorise,dc=xxx,dc=xxx,dc=xxx)## User Entries: 
Array
(
    [count] => 0
)

**Comment by ReeceYoung98** [comment]
Just a thought: Would it possibly be something to do with 'Login Attribute' and 'Name Attribute' not saving in the LDAP config?

The login would be looking for 'SAMAccountName' although in my LDAP attributes it is uid maybe?

When clicking the 'Import' button on the Users page, it doesn't import as login and name attribute isn't saved, and thus looking for the wrong values.

**Comment by nuxsmin** [comment]
You're right, the import from the users page will fail, because the login and name attribute weren't saved. These attributes aren't saved in the config because they are used only once, so I didn't implement that behavior.

The `SAMAccountName` is used only in this piece of code but the app will look for either `SAMAccountName`, `cn`or `uid`. You can change it to check out if there is any result.

**Comment by ReeceYoung98** [comment]
Changing to `cn` or `uid` didn't have any affect in the test LDAP.

I just noticed in your GIST had ':1.2.840.113556.1.4.1941:' included in the memberof.

I have removed this and all my users are displayed for example:
[count] => 721
    [0] => Array
        (
            [count] => 0
            [dn] => uid=username,ou=people,ou=central,dc=authorise,dc=xxx,dc=xxx,dc=xxx
        )

    [1] => Array
        (
            [count] => 0
            [dn] => uid=username,ou=people,ou=central,dc=authorise,dc=xxx,dc=xxx,dc=xxx
        )

**Comment by nuxsmin** [comment]
Ok, that special hack is to look for nested group membership, which is available on ADS. Are you using Active Directory? If so, which version?

**Comment by ReeceYoung98** [comment]
I have now managed to get this working - I presumed we were using AD although we actually don't.

We're a sub-entity, and so couldn't check.

Thanks for all your work on this! As I mentioned, the import attributes being saved in the config would be great for importing LDAP users from the users page.

**Comment by nuxsmin** [comment]
Nice, I'm glad to know it's working fine.

Regarding the import attributes, you're right, they should be saved​ to avoid any hassle when importing.

Regards

**Comment by kevthanewversi** [comment]
So guys, @ReeceYoung98 and @nuxsmin adding in a **ldapUserattr** config in the config.xml file will should work right? Is it an array? Would anyone of you guys share a gist on how you added it..?
